판다스 데이터 선택

열 선택하기

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('weather.csv')
df

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [3]:
df['temp']

0       28.7
1       25.2
2       22.1
3       25.3
4       27.2
        ...
3648    22.1
3649    21.9
3650    21.6
3651    22.9
3652    25.7
Name: temp, Length: 3653, dtype: float64

In [4]:
df.temp

0       28.7
1       25.2
2       22.1
3       25.3
4       27.2
        ...
3648    22.1
3649    21.9
3650    21.6
3651    22.9
3652    25.7
Name: temp, Length: 3653, dtype: float64

In [5]:
type(df['temp'])

pandas.Series

여러 컬럼 선택하기

In [6]:
df[['date','temp']]

            date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

In [7]:
type(df[['date','temp']])

pandas.DataFrame

## loc 
-데이터프레임명.loc[행, 열]

In [8]:
df.head()

         date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9
3  2010-08-04  25.3       6.6        4.2
4  2010-08-05  27.2       9.1        5.6

In [9]:
df.loc['temp'] # 행을 안적고 열만 적으면 오류 발생!

KeyError: 'temp'

In [10]:
df.loc[0,'temp']

np.float64(28.7)

In [11]:
print(df.loc[0,'temp'])

28.7

In [ ]:
df.loc[0] # 열은 생략 가능

date         2010-08-01
temp               28.7
max_wind            8.3
mean_wind           3.4
Name: 0, dtype: object

In [ ]:
df.loc[:, 'temp']  #df[temp] 차이점 확인하기 df.loc[행, 열]좀 더 구체적으로 확인가능

0       28.7
1       25.2
2       22.1
3       25.3
4       27.2
        ...
3648    22.1
3649    21.9
3650    21.6
3651    22.9
3652    25.7
Name: temp, Length: 3653, dtype: float64

In [14]:
df.loc[:, ['date', 'temp']]

            date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

In [19]:
df.loc[:, ['date', 'max_wind']]

            date  max_wind
0     2010-08-01       8.3
1     2010-08-02       8.7
2     2010-08-03       6.3
3     2010-08-04       6.6
4     2010-08-05       9.1
...          ...       ...
3648  2020-07-27       4.2
3649  2020-07-28       4.5
3650  2020-07-29       3.2
3651  2020-07-30       9.7
3652  2020-07-31       4.8

[3653 rows x 2 columns]

In [30]:
df.loc[:, 'date': 'max_wind']

            date  temp  max_wind
0     2010-08-01  28.7       8.3
1     2010-08-02  25.2       8.7
2     2010-08-03  22.1       6.3
3     2010-08-04  25.3       6.6
4     2010-08-05  27.2       9.1
...          ...   ...       ...
3648  2020-07-27  22.1       4.2
3649  2020-07-28  21.9       4.5
3650  2020-07-29  21.6       3.2
3651  2020-07-30  22.9       9.7
3652  2020-07-31  25.7       4.8

[3653 rows x 3 columns]

## iloc
- i는 정수라는 뜻
- 데이터프레임명.iloc[행번호, 열번호]

In [20]:
df.iloc[0,1]

np.float64(28.7)

In [22]:
df.head(3)

         date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9

In [23]:
df.iloc[1:3] # 1,2번 행 (3번행은 포함하지 않는다), 열번호는 생략가능

         date  temp  max_wind  mean_wind
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9

In [ ]:
df.iloc[:, 0:2] # 행은 전체, 열은 0~1까지(2번 열은 포함하지 않는다.)

            date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

In [26]:
df.iloc[1:4, 0:3]

         date  temp  max_wind
1  2010-08-02  25.2       8.7
2  2010-08-03  22.1       6.3
3  2010-08-04  25.3       6.6

## 불(bool) 인덱싱
-

In [ ]:
w= df['max_wind'] >= 10  #True인 값만 보여줌
df[w]

            date  temp  max_wind  mean_wind
9     2010-08-10  25.6      10.2        5.5
12    2010-08-13  24.3      10.9        4.6
13    2010-08-14  25.0      10.8        4.4
14    2010-08-15  24.5      16.9       10.3
29    2010-08-30  26.2      10.5        6.2
...          ...   ...       ...        ...
3622  2020-07-01  16.8      19.7        8.7
3632  2020-07-11  20.1      10.3        4.1
3634  2020-07-13  17.8      10.3        4.6
3635  2020-07-14  17.8      12.7        9.4
3641  2020-07-20  23.0      11.2        7.3

[830 rows x 4 columns]

In [38]:
df[df['max_wind'] >= 10]

            date  temp  max_wind  mean_wind
9     2010-08-10  25.6      10.2        5.5
12    2010-08-13  24.3      10.9        4.6
13    2010-08-14  25.0      10.8        4.4
14    2010-08-15  24.5      16.9       10.3
29    2010-08-30  26.2      10.5        6.2
...          ...   ...       ...        ...
3622  2020-07-01  16.8      19.7        8.7
3632  2020-07-11  20.1      10.3        4.1
3634  2020-07-13  17.8      10.3        4.6
3635  2020-07-14  17.8      12.7        9.4
3641  2020-07-20  23.0      11.2        7.3

[830 rows x 4 columns]

조건에 맞는 데이터 추출

In [ ]:
# 최고로 바람이 강했던 날  정보(행)
w = df['max_wind'] == df['max_wind'].max()
df[w]

            date  temp  max_wind  mean_wind
2988  2018-10-06  19.4      26.0        7.0

## 조건이 2개 이상 --> 그리고 &, 또는 |

In [ ]:
## 기온이 30도 이상이고, 최대 풍속이 9이상인 데이터

w =(df['temp'] >= 30) | (df['max_wind'] >= 9)  # or, 또는
df[w]

            date  temp  max_wind  mean_wind
4     2010-08-05  27.2       9.1        5.6
5     2010-08-06  26.8       9.8        8.0
6     2010-08-07  27.5       9.1        5.0
9     2010-08-10  25.6      10.2        5.5
10    2010-08-11  24.6       9.4        4.8
...          ...   ...       ...        ...
3632  2020-07-11  20.1      10.3        4.1
3634  2020-07-13  17.8      10.3        4.6
3635  2020-07-14  17.8      12.7        9.4
3641  2020-07-20  23.0      11.2        7.3
3651  2020-07-30  22.9       9.7        2.4

[1218 rows x 4 columns]

In [ ]:
## 기온이 30도 이상이고, 최대 풍속이 9이상인 데이터

w =(df['temp'] >= 30) & (df['max_wind'] >= 9) # and, 그리고
df[w]

            date  temp  max_wind  mean_wind
1104  2013-08-09  30.6       9.9        6.4

# 판다스 결측데이터 처리

- isna() --> 값이 nan(결측치)이라면   True

In [48]:
# 최대 풍속이 측정되지 않은 모든 데이터 출력

df['max_wind'].isna()

0       False
1       False
2       False
3       False
4       False
        ...
3648    False
3649    False
3650    False
3651    False
3652    False
Name: max_wind, Length: 3653, dtype: bool

In [46]:
df[df['max_wind'].isna()]

            date  temp  max_wind  mean_wind
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

## 데이터프레임명.isnull().sum() --> 컬럼별 결측데이터 개수

- 0 False 거짓
- 1 True 참

In [ ]:
df.isnull()  #isna()는 결과를 NaN, isnull()은 결과를 True or False로 보여줌

       date   temp  max_wind  mean_wind
0     False  False     False      False
1     False  False     False      False
2     False  False     False      False
3     False  False     False      False
4     False  False     False      False
...     ...    ...       ...        ...
3648  False  False     False      False
3649  False  False     False      False
3650  False  False     False      False
3651  False  False     False      False
3652  False  False     False      False

[3653 rows x 4 columns]

In [ ]:

df.isnull().sum()  #결측치 갯수

date         0
temp         0
max_wind     4
mean_wind    6
dtype: int64

# 결측데이터 삭제하기 --> dropna()

In [ ]:
df.dropna() #결측치를 제거한 상태를 한번 보는 용도

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3646 rows x 4 columns]

In [53]:
df2 = df.dropna() # 결측치 삭제한 데이터들을 새로운 테이터프레임에 저장
df2

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3646 rows x 4 columns]

In [54]:
df2.isnull().sum()

date         0
temp         0
max_wind     0
mean_wind    0
dtype: int64

## 결측데이터 대체하기 --> fillna(채울 값)

In [67]:
df['max_wind'].isnull().sum()

np.int64(4)

In [56]:
df3 = df.copy() #복사
df3

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [57]:
df3 = df3.fillna(0)

In [58]:
df3.isnull().sum()

date         0
temp         0
max_wind     0
mean_wind    0
dtype: int64

In [59]:
# 평균 --> mean()
avg =df3['max_wind'].mean()
avg

np.float64(7.902436353681905)

In [ ]:
df3['max_wind'] = df3['max_wind'].fillna(avg)

In [61]:
avg2 = df3['mean_wind'].mean()
avg2

np.float64(3.9299753627155765)

In [62]:
df3['mean_wind'] = df3['mean_wind'].fillna(avg2)

In [63]:
df3.tail(10)

            date  temp  max_wind  mean_wind
3643  2020-07-22  22.2       4.3        1.9
3644  2020-07-23  21.5       4.9        2.3
3645  2020-07-24  20.4       7.2        2.8
3646  2020-07-25  20.7       3.8        1.1
3647  2020-07-26  21.4       4.8        2.8
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5