In [106]:
import pandas as pd
import numpy as np

In [107]:
# ex)2-1 covid.csv 파일 불러와서 데이터 확인하기
# 한글파일 깨지는 문제 해결 : encoding='cp949'

covid = pd.read_csv('covid.csv', encoding='cp949')
covid

       항목  사례수    증가    감소  변화없음
0    스마트폰  999  78.9   1.7  19.4
1    텔레비전  965  68.5   3.9  27.6
2  개인용 PC  973  65.7   3.7  30.6
3  태블릿 PC  662  46.8   4.2  49.0
4     라디오  687  35.5  12.5  52.0
5    잡지·책  776  31.3  17.8  50.9
6    종이신문  552  17.6  23.2  59.2

In [108]:
# 인덱스 행으로 컬럼시작하기(쌤)

covid = pd.read_csv('covid.csv', index_col=0, encoding='cp949')
covid

        사례수    증가    감소  변화없음
항목
스마트폰    999  78.9   1.7  19.4
텔레비전    965  68.5   3.9  27.6
개인용 PC  973  65.7   3.7  30.6
태블릿 PC  662  46.8   4.2  49.0
라디오     687  35.5  12.5  52.0
잡지·책    776  31.3  17.8  50.9
종이신문    552  17.6  23.2  59.2

In [109]:
# ex)2-2 사례수가 가장 높은 항목의 모든 정보를 출력하기

covid1 = covid.sort_values(by='사례수', ascending= False)
covid1.head(1)

      사례수    증가   감소  변화없음
항목
스마트폰  999  78.9  1.7  19.4

In [110]:
# 사례수가 가장 높은 것(쌤)
covid['사례수'].max()

np.int64(999)

In [111]:
# 스마트폰이 가장 높다 -> 그 행 다 추출(쌤)

covid[covid['사례수'] == covid['사례수'].max()]

      사례수    증가   감소  변화없음
항목
스마트폰  999  78.9  1.7  19.4

In [112]:
# ex)2-3 증가율이 높은 3개의 항목 출력하기
 
covid3 = covid.sort_values(by='증가', ascending= False)
covid3.head(3)

        사례수    증가   감소  변화없음
항목
스마트폰    999  78.9  1.7  19.4
텔레비전    965  68.5  3.9  27.6
개인용 PC  973  65.7  3.7  30.6

In [113]:
# 증가율이 높은 3개 --> 정렬 --> 내림차순(쌤)

covid3 = covid.sort_values(by='증가', ascending= False)
covid3.head(3)

        사례수    증가   감소  변화없음
항목
스마트폰    999  78.9  1.7  19.4
텔레비전    965  68.5  3.9  27.6
개인용 PC  973  65.7  3.7  30.6

In [114]:
# ex)3

vaccine = pd.read_csv('vaccine.csv', encoding='cp949')

vaccine

,date,subject,day1num,day1sum,day1rate,day2num,day2sum,day2rate
0,2021.10.16,9505868,10673,7562283,79.6,66910,6191341,65.1
1,2021.10.15,9505868,14556,7551829,79.4,133580,6124432,64.4
2,2021.10.14,9505868,9609,7536654,79.3,94569,5989111,63.0
3,2021.10.13,9505868,9804,7526430,79.2,77503,5893191,62.0
4,2021.10.12,9505868,17274,7516070,79.1,110204,5814018,61.2
...,...,...,...,...,...,...,...,...
174,2021.04.25,1023346,23323,350631,34.2,3411,18513,1.8
175,2021.04.24,1023346,200,350427,34.2,0,18513,1.8
176,2021.04.23,1027740,10195,345764,33.6,119,18376,1.8
177,2021.04.22,1023538,27074,317386,31.0,2479,15901,1.6
178,2021.04.21,1019322,22501,291857,28.6,2358,13543,1.3

In [115]:
# ex) 3-1  하위 5행의 데이터를 확인하기

vaccine.tail(5)

,date,subject,day1num,day1sum,day1rate,day2num,day2sum,day2rate
174,2021.04.25,1023346,23323,350631,34.2,3411,18513,1.8
175,2021.04.24,1023346,200,350427,34.2,0,18513,1.8
176,2021.04.23,1027740,10195,345764,33.6,119,18376,1.8
177,2021.04.22,1023538,27074,317386,31.0,2479,15901,1.6
178,2021.04.21,1019322,22501,291857,28.6,2358,13543,1.3

In [116]:
# ex) 3-2 필요없는 열 삭제하기
# axis=1  열(컬럼)기준으로 지우기. 미지기입시 행이 지워짐.

vaccine1 = vaccine.drop(['day1sum', 'day1rate', 'day2sum', 'day2rate'], axis=1)
vaccine1

           date  subject  day1num  day2num
0    2021.10.16  9505868    10673    66910
1    2021.10.15  9505868    14556   133580
2    2021.10.14  9505868     9609    94569
3    2021.10.13  9505868     9804    77503
4    2021.10.12  9505868    17274   110204
..          ...      ...      ...      ...
174  2021.04.25  1023346    23323     3411
175  2021.04.24  1023346      200        0
176  2021.04.23  1027740    10195      119
177  2021.04.22  1023538    27074     2479
178  2021.04.21  1019322    22501     2358

[179 rows x 4 columns]

In [117]:
# ex) 3-3 기초통계량 확인하기
# describe()

vaccine1.describe()

            subject        day1num        day2num
count  1.790000e+02     179.000000     179.000000
mean   5.086644e+06   40078.150838   34096.636872
std    3.324235e+06   44231.469656   40745.688278
min    1.019322e+06       0.000000       0.000000
25%    2.279241e+06    4385.000000    4794.500000
50%    3.943320e+06   23323.000000   16581.000000
75%    9.505868e+06   71634.500000   50950.000000
max    9.795426e+06  169036.000000  200186.000000

In [118]:
# ex) 3-4 월별 1차접종사, 2차접종자수 컬럼의 평균을 출력하세요.


vaccine1['date'] = pd.to_datetime(vaccine1['date'] )
vaccine1.info()

<class 'pandas.DataFrame'>
RangeIndex: 179 entries, 0 to 178
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     179 non-null    datetime64[us]
 1   subject  179 non-null    int64
 2   day1num  179 non-null    int64
 3   day2num  179 non-null    int64
dtypes: datetime64[us](1), int64(3)
memory usage: 5.7 KB

In [119]:
vaccine1['month'] = vaccine1['date'].dt.month
vaccine1

          date  subject  day1num  day2num  month
0   2021-10-16  9505868    10673    66910     10
1   2021-10-15  9505868    14556   133580     10
2   2021-10-14  9505868     9609    94569     10
3   2021-10-13  9505868     9804    77503     10
4   2021-10-12  9505868    17274   110204     10
..         ...      ...      ...      ...    ...
174 2021-04-25  1023346    23323     3411      4
175 2021-04-24  1023346      200        0      4
176 2021-04-23  1027740    10195      119      4
177 2021-04-22  1023538    27074     2479      4
178 2021-04-21  1019322    22501     2358      4

[179 rows x 5 columns]

In [122]:
# 월별 day1num, day2num

vaccine2 = vaccine1[['day1num', 'day2num', 'month']]
vaccine2.head()

   day1num  day2num  month
0    10673    66910     10
1    14556   133580     10
2     9609    94569     10
3     9804    77503     10
4    17274   110204     10

In [130]:
# 월별 day1num, day2num

vaccine2.groupby('month').mean()

            day1num       day2num
month
4      22060.100000   2304.600000
5      18225.548387   9734.000000
6      55957.200000  20147.300000
7      25807.870968   9934.903226
8      57667.258065  55575.000000
9      65715.000000  62162.000000
10      9406.312500  79900.750000

In [124]:
# ex) 4

df1 =pd.read_csv('signup.csv', encoding='cp949')
df1

   수강코드    과목명 담당교수
0   111    파이썬  양숙희
1   222  데이터분석  오경선
2   333   인공지능  장은실
3   444   선형대수  황복동
4   555   이산수학  정명식
5   666  컴퓨터개론  최봉수
6   777   자료구조  김진영
7   888   정보통신  김진호

In [126]:
df2 =pd.read_csv('professor.csv', encoding='cp949')
df2

  담당교수     학과
0  양숙희  컴퓨터공학
1  장은실   정보통신
2  오경선   인공지능
3  황복동  컴퓨터공학
4  정명식   인공지능

In [127]:
# ex) merge()

df = pd.merge(df1, df2, on='담당교수')
df

   수강코드    과목명 담당교수     학과
0   111    파이썬  양숙희  컴퓨터공학
1   222  데이터분석  오경선   인공지능
2   333   인공지능  장은실   정보통신
3   444   선형대수  황복동  컴퓨터공학
4   555   이산수학  정명식   인공지능

In [129]:
# 교수테이블에서 학과별 인원수 출력하기
# 학과별 인원수 --> 그룹 --> count()
df3 = df[['담당교수', '학과']]
df3 = df3.groupby('학과').count()
df3

       담당교수
학과
인공지능      2
정보통신      1
컴퓨터공학     2